---
title: "R Notebook"
output: html_notebook
---

##Instructions
1. create a data frame with the column that indicates edible or oisonous and three or four other columns.  
2. Add meaningful column names
3. Replace the abbreviations used

Your deliverable is the R code to perform these transformation tasks. 

### Load libaries
```{r Load Libraries}
library(data.table)
library(dplyr)
library(tidyr)
library(magrittr)
```

### Load data and column labels, then apply labels to data
```{r Data Import}
mushdata <- fread("mush.data", header = FALSE)
```

```{r}
mushlabels <- as.character(fread("keycolumns.csv", header = FALSE))
```

```{r}
names(mushdata) <- mushlabels
```


###Get Key to rename labels
```{r}
keydata <- fread("key.csv", header = TRUE)
```

```{r}
keydata2 <- data.table(keydata)
mushdata2 <- data.table(mushdata)
```


### Change Values

```{r Add labels gave 124, dplyr ********}
#df2 %>% gather(Group, Name) %>% left_join(., df1) %>% select(-Name) %>% group_by(Group) %>% mutate(r = row_number()) %>% spread(Group, Vote) %>% select(-r)

mushdata %>% gather(keycat, letterkey) %>% left_join(., keydata) %>% select(-letterkey) %>% group_by(keycat) %>% mutate(r = row_number()) %>% spread(keycat, keylabel) %>% select(-r)

```


```{r Solution based on data.table WORKS, 127}
test <- melt(setDT(mushdata), measure.vars = 1:23)[keydata, on = .(variable = keycat, value = letterkey)][, dcast(.SD, rowid(variable) ~ variable, value.var = 'keylabel')][, variable := NULL][]
```

```{r}
mushdata %>% gather(keycat, letterkey) %>% left_join(., key) %>% select(-letterkey) %>% group_by(keycat) %>% mutate(r = row_number()) %>% spread(keycat, keylabel) %>% select(-r)
```

#Subset


```{r Subset, works, keeps labels}
#smaldf <- data.frame(fmushdata$`bruises?`,fmushdata$`cap-shape`)
subset1 <- subset(test, select=c('gill-size','gill-attachment'))
```


```{r Option for subset, it works but loses labels}
subset2 <- data.table(test$`edible?`,test$`cap-shape`,test$`cap-surface`)
```

